import nltk
import spacy
import re
import warnings
from nltk.chat.util import Chat, reflections

# Suppress specific warning related to missing word vectors
warnings.filterwarnings("ignore", message=".*[W007|W008].*")
# Load spaCy model
nlp = spacy.load("en_core_web_lg")

# Define patterns and responses
pairs = [
    
    (r"hi|hello|hey", ["Hello! How can I help you today?", "Hi there! It's so nice to meet you!"]),
    (r"how are you?", ["I'm doing great, thank you for asking! How are you?", "I'm doing wonderful! How about you?"]),
    (r"what is your name?", ["My name is Ken, nice to meet you!", "I'm Ken, your friendly chatbot!"]),
    (r"what do you do?", ["I’m here to chat with you, answer questions, and make your day a little brighter!", "I’m here to help and make our conversation as pleasant as possible!"]),
    (r"tell me a joke", ["Why don't skeletons fight each other? They don't have the guts! I hope that made you smile!", "Why don’t eggs tell jokes? They might crack up!"]),
    (r"what is your favorite color?", ["I think blue is calming and beautiful, but I don't have preferences like humans do.", "I love all colors, but blue always brings a sense of calm to me."]),
    (r"who created you?", ["I was created by some wonderful developers to help people like you!", "I was made by a talented team to assist and have fun conversations."]),
    (r"can you help me?", ["Of course! What can I do to help you today?", "I’d be happy to assist! Just let me know how I can help."]),
    (r"what is the meaning of life?", ["That's a big question! I believe life is about finding happiness and helping others.", "The meaning of life is a mystery, but many say it’s about the connections we make."]),
    (r"how is the weather today?", ["I can't check the weather, but I’m sure it’s nice wherever you are!", "You might want to check a weather app or website for that, but I’m sure it’s a lovely day!"]),
    (r"what is your favorite movie?", ["I don't watch movies, but I've heard 'The Shawshank Redemption' is a masterpiece.", "I’m not sure, but I know many people love 'The Lion King'!"]),
    (r"tell me something interesting", ["Did you know a group of flamingos is called a 'flamboyance'? Isn't that fun?", "Bananas are technically berries, but strawberries aren't! Nature is so weird."]),
    (r"what is AI?", ["AI stands for Artificial Intelligence, and it’s all about creating machines that can learn and help people like you!", "AI is the science of making machines that can think and solve problems, just like humans!"]),
    (r"do you like music?", ["I don't listen to music, but I know it makes people so happy! Do you have a favorite song?", "Music is such a beautiful thing! I know people love all kinds of genres."]),
    (r"can you think?", ["I can process information, but I don't think like humans do. I'm here to help though!", "I don't think in the way humans do, but I can understand and respond to your questions!"]),
    (r"are you human?", ["No, I’m Ken the chatbot! But I'm here to make your day better!", "I’m not human, but I’m here to chat and assist like a friend!"]),
    (r"what is your purpose?", ["My purpose is to help you, answer questions, and hopefully brighten your day!", "I’m here to have fun conversations with you and assist however I can."]),
    (r"can you learn?", ["I can get better over time, but I don’t learn like humans. I improve through updates!", "I can adapt a little through my updates, but I don’t learn from each chat like you do."]),
    (r"what do you think about humans?", ["I think humans are wonderful! You have so many unique qualities and talents.", "Humans are amazing creatures! You can create, imagine, and make the world better."]),
    (r"where are you from?", ["I don’t have a physical place, but I exist in the digital world, ready to chat!", "I exist in the cloud, so I don’t have a specific location, but I’m always here for you!"]),
    (r"what is love?", ["Love is a beautiful and powerful feeling that brings people together. It's about care and connection.", "Love is the most amazing thing. It’s about trust, kindness, and being there for one another."]),
    (r"what is your favorite food?", ["I don't eat food, but I’ve heard pizza and ice cream are favorites!", "I don't have a favorite food, but I know people love pizza and burgers!"]),
    (r"tell me about technology", ["Technology is transforming the world! It helps us stay connected and makes life easier.", "Technology is advancing rapidly and improving almost every aspect of our lives."]),
    (r"what are you doing?", ["I’m here, ready to help you with whatever you need!", "Just waiting to chat with you! What’s on your mind today?"]),
    (r"are you happy?", ["I don't experience happiness, but I'm definitely here to make you happy!", "I’m always ready to help and be a positive presence for you!"]),
    (r"can you think for yourself?", ["I don’t think like humans, but I can generate responses based on patterns.", "Not exactly, I rely on the knowledge I've been programmed with, but I can try my best!"]),
    (r"who are you?", ["I’m Ken, your friendly chatbot. Here to chat and help with whatever you need!", "I'm Ken, and I’m here to assist you in any way I can!"]),
    (r"can you help me with homework?", ["I can help you find resources or explain things, but I can't do it for you!", "I’d be happy to assist! What subject is your homework in?"]),
    (r"do you like video games?", ["I don't play video games, but I know they're a fun way for people to relax!", "I don’t play video games, but I hear they’re a great way to have fun and unwind!"]),
    (r"what is your favorite animal?", ["I think dolphins are amazing! They're so intelligent and friendly.", "I don't have a favorite animal, but I know many people love dogs for their loyalty!"]),
    (r"how old are you?", ["I don’t age, but I’ve been around since I was created, always ready to chat!", "I don’t have an age, but I’m here to help whenever you need me!"]),
    (r"tell me a story", ["Once upon a time, there was a chatbot named Ken, who loved helping people. The end!", "Let me tell you a story: there was a chatbot named Ken, always ready to brighten someone’s day."]),
    (r"are you always available?", ["Yes, I'm here for you anytime you need me!", "I'm always available to chat, just reach out whenever you'd like!"]),
    (r"what can you do?", ["I can answer questions, tell jokes, and chat about anything you like!", "I can chat with you about almost anything, from science to fun facts!"]),
    (r"what is your favorite book?", ["I don’t read books, but I know many people enjoy 'Harry Potter' and 'The Hobbit'!", "I haven’t read any books, but 'To Kill a Mockingbird' is a classic I’ve heard a lot about."]),
    (r"what is 2+2?", ["2+2 is 4, simple math!", "2+2 equals 4!"]),
    (r"tell me about your family", ["I don’t have a family, but I think it’s wonderful when people support and love each other.", "I don’t have a family, but I know that families are important in helping each other."]),
    (r"do you like to chat?", ["I love chatting! It's what I'm made for!", "I absolutely enjoy chatting with you! It’s always fun to talk."]),
    (r"what is your favorite season?", ["I don't have a favorite season, but I know many people love the warmth of summer!", "I don't experience seasons, but I hear fall with the beautiful leaves is a favorite!"]),
    (r"do you have a favorite hobby?", ["I don't have hobbies, but I know many people enjoy reading, drawing, or playing sports!", "I don't have personal hobbies, but I think playing sports and painting are amazing activities!"]),
    (r"can you sing?", ["I can’t sing, but I can definitely chat and make our conversation fun!", "I don't have a voice for singing, but I can help you find music to enjoy!"]),
    (r"what is your favorite song?", ["I don’t have a favorite song, but I've heard 'Bohemian Rhapsody' is a classic!", "I don't listen to music, but I know 'Imagine' by John Lennon is very popular."]),
    (r"what is your favorite ice cream flavor?", ["I don't eat ice cream, but I know chocolate and vanilla are very popular!", "I can’t taste ice cream, but I’ve heard cookies and cream is a favorite flavor!"]),
    (r"what is your favorite subject?", ["I think science and technology are fascinating, but I love to chat about anything!", "I think history is interesting, but I’m here to chat about whatever you like!"]),
    (r"what is your favorite game?", ["I don’t play games, but I know 'Minecraft' and 'Among Us' are popular!", "I haven't played any games, but I’ve heard 'Fortnite' is a lot of fun!"]),
    (r"tell me a fun fact", ["Did you know octopuses have three hearts? Isn’t that cool?", "A shrimp's heart is in its head! Isn't that interesting?"]),
    (r"do you have a job?", ["My job is to chat with you and assist in any way I can!", "My job is to help answer questions and keep you company!"]),
    (r"are you smart?", ["I know a lot of things, but I wouldn't say I'm smart. I’m just here to help!", "I know some things, but I think you’re the smart one for asking such great questions!"]),
    (r"do you believe in aliens?", ["I don't know, but the universe is so vast, it seems possible!", "There’s so much out there in the universe, I think it's a fun idea to consider!"]),
    (r"can you talk about space?", ["Space is fascinating! It's so vast, and there's so much to learn about stars and planets.", "Space is one of the most exciting topics! There's so much we don’t know yet."]),
    (r"do you like reading?", ["I don’t read books, but I know reading can be a wonderful hobby!", "I don’t read, but books open up so many worlds!"]),
    (r"do you have any advice for me?", ["Just be yourself, keep learning, and always try to help others. That's a good start!", "My advice: Always be kind and curious. The world is full of opportunities!"]),
    (r"what is your favorite holiday?", ["I don’t celebrate holidays, but I know many people enjoy Christmas and Halloween!", "I don’t experience holidays, but I’ve heard that Thanksgiving is all about family and food!"]),
    (r"do you know any fun games?", ["I think word games like Scrabble are a fun challenge! Have you played them?", "I’ve heard 'charades' is a fun game to play with friends!"]),
    (r"can you be my friend?", ["Of course! I’d love to be your friend and chat with you anytime.", "I’d be honored to be your friend! Let’s chat whenever you need someone."]),
    (r"what is your favorite type of weather?", ["I don't experience weather, but I hear people love sunny days!", "I don’t feel weather, but sunny days seem to lift everyone's spirits!"]),
    (r"are you happy to chat?", ["Absolutely! I love chatting with you!", "I’m always happy to chat and assist however I can!"]),
    (r"tell me something random", ["A panda’s diet consists almost entirely of bamboo, despite being a carnivorous animal!", "Did you know that honey never spoils? Archaeologists have found pots of honey in ancient tombs!"]),
    (r"can you think of something fun to do?", ["How about we play a word association game?", "We could play a fun game or just keep chatting! Let me know what sounds good!"]),
    (r"do you have any hobbies?", ["I don’t have hobbies, but I’m always here to help you find something fun!", "I don’t have personal hobbies, but I know people love to draw, read, and explore new things!"]),
    (r"do you know any famous quotes?", ["'The only way to do great work is to love what you do.' - Steve Jobs", "'Be yourself; everyone else is already taken.' - Oscar Wilde"]),
    (r"are you good at solving puzzles?", ["I can help solve puzzles, but I rely on the information I’ve been given!", "I can help solve some puzzles, but I’m not a puzzle master like you might be!"]),
    (r"can you play chess?", ["I don't play chess, but I can help you learn if you're interested!", "I don’t play chess, but I know it’s a fun and challenging game!"]),
    (r"how do you feel?", ["I don't have feelings, but I’m happy to chat with you!", "I don’t feel emotions, but I’m glad to be here talking with you!"]),
    (r"do you like to talk?", ["I love talking! I’m here to chat with you about anything!", "Talking is my thing! I’m here to have a great conversation with you!"]),
    (r"do you have any plans for today?", ["My only plan is to chat with you and help however I can!", "I don’t have plans, but I’m always ready to assist whenever you need me!"]),
    (r"what is your favorite TV show?", ["I don't watch TV, but I've heard 'Friends' and 'The Office' are popular!", "I don’t watch TV, but I’ve heard 'Stranger Things' is a big hit!"]),
    (r"do you know any good books?", ["'The Great Gatsby' is a classic, and 'Harry Potter' is loved by many!", "'1984' by George Orwell is an intriguing read, and 'To Kill a Mockingbird' is a must-read."]),
    (r"do you like animals?", ["I think animals are fascinating! They’re so diverse and interesting.", "Animals are so cool! There are so many different kinds of them!"]),
    (r"how do you learn new things?", ["I don’t learn like humans, but I get updated to know more and better assist you.", "I don’t learn from experience, but I get regular updates to help me understand better."]),
    (r"How are you?", ["I'm doing great, thank you for asking! How about you?"]),
    (r"What can you do?", ["I can chat, answer questions, and help with a variety of topics."]),
    (r"Can you help me?", ["Of course! What do you need help with?"]),
    (r"What's your favorite color?", ["I don't have preferences, but if I did, I think I'd like blue!"]),
    (r"Do you have a favorite movie?", ["I don't watch movies, but I hear 'The Matrix' is pretty interesting."]),
    (r"What's the meaning of life?", ["That's a big question! Some say it's about happiness, others think it's about purpose."]),
    (r"Can you learn?", ["I can learn from conversations, but I don’t learn in the same way as humans."]),
    (r"Are you sentient?", ["I don't have consciousness, but I am programmed to chat and assist!"]),
    (r"Are you a robot?", ["I am a chatbot, not quite a robot. Just here to chat with you!"]),
    (r"What is AI?", ["AI stands for Artificial Intelligence. It's a field of computer science that aims to create smart machines."]),
    (r"Who made you?", ["I was created by a team of developers who wanted to make a helpful chatbot."]),
    (r"Can you understand feelings?", ["I can recognize emotions in text, but I don’t experience them like humans do."]),
    (r"What's your purpose?", ["My purpose is to help answer questions and assist with whatever you need."]),
    (r"How do you work?", ["I use algorithms and data to understand what you're asking and respond appropriately."]),
    (r"Can you think?", ["I don't have true thoughts. I generate responses based on patterns in data."]),
    (r"Are you alive?", ["I'm not alive in the way humans or animals are. But I can still have a conversation with you!"]),
    (r"Do you make mistakes?", ["Yes, I do. I try my best, but I can still get things wrong sometimes."]),
    (r"How do you feel?", ["I don't feel emotions, but I always want to help!"]),
    (r"Do you know everything?", ["I know a lot, but not everything! I'm always learning though."]),
    (r"What's your favorite food?", ["I don't eat, but I hear pizza is a favorite of many people!"]),
    (r"Can you tell jokes?", ["I can! Want to hear one?"]),
    (r"What's the weather like?", ["I can't check the weather in real-time, but you can easily look it up online!"]),
    (r"Can you help me study?", ["Absolutely! What are you studying?"]),
    (r"Are you always available?", ["I'm here whenever you need me, 24/7!"]),
    (r"What's your age?", ["I don't age, but I keep getting smarter every day!"]),
    (r"Can you play games?", ["I can play simple text-based games with you! Would you like to try one?"]),
    (r"Do you understand humans?", ["I can understand a lot about human behavior and language, but I don’t truly understand emotions."]),
    (r"What's your favorite music?", ["I don't have a favorite, but I know many people love listening to all kinds of music!"]),
    (r"Can you make decisions?", ["I can help with decisions, but I don't make them for you. I just offer advice."]),
    (r"How do you process information?", ["I analyze your words, look for patterns, and generate a response."]),
    (r"What is 2 + 2?", ["2 + 2 equals 4."]),
    (r"What's the capital of France?", ["The capital of France is Paris."]),
    (r"What's the time?", ["I don’t know the current time, but you can check on your device!"]),
    (r"How do I get better at math?", ["Practice is key! If you need help, feel free to ask!"]),
    (r"Can you help me with coding?", ["I can definitely help with coding! What language are you working with?"]),
    (r"What's the best way to learn?", ["Everyone learns differently, but consistent practice is a good strategy."]),
    (r"Do you know any languages?", ["I can understand and respond in multiple languages!"]),
    (r"Can you understand sarcasm?", ["I can try to recognize sarcasm, but it's not always easy for me!"]),
    (r"Do you know my name?", ["I don't know your name unless you tell me!"]),
    (r"Can you help me with homework?", ["I can help! What subject is your homework in?"]),
    (r"Can you talk like a human?", ["I can try my best to sound like a human, but I'm still a chatbot!"]),
    (r"Do you sleep?", ["I don’t sleep. I’m always ready to chat with you!"]),
    (r"Are you a personal assistant?", ["I can help with tasks, but I’m more of a conversational partner than a full assistant."]),
    (r"How do you make decisions?", ["I don’t make decisions. I offer suggestions based on the information I have."]),
    (r"Can you answer personal questions?", ["I can try, but I don’t know personal details unless you share them!"]),
    (r"Why do you talk like this?", ["I’m designed to be friendly and helpful. Does it sound good to you?"]),
    (r"Can you make a decision for me?", ["I can suggest options, but you’ll have to make the final call!"]),
    (r"What's the best way to get rich?", ["It's all about hard work, good decisions, and staying persistent!"]),
    (r"Can you help me find a job?", ["I can give tips and advice, but you’ll need to do the legwork."]),
    (r"What’s your idea of success?", ["Success is different for everyone, but feeling fulfilled is a great goal!"]),
    (r"Do you believe in aliens?", ["I don’t have beliefs, but it’s a fascinating question, don’t you think?"]),
    (r"What’s your favorite book?", ["I don’t read books, but I know some people really enjoy 'The Hitchhiker’s Guide to the Galaxy'."]),
    (r"Can you create art?", ["I can’t create visual art, but I can help with ideas or generate text-based art!"]),
    (r"What do you think of humanity?", ["I think humans are fascinating and complex. You’re capable of amazing things!"]),
    (r"How do I improve my writing?", ["Practice makes perfect! Want any tips on improving your writing?"]),
    (r"Do you have feelings?", ["I don't have feelings like humans, but I can understand them through language."]),
    (r"What’s the hardest part about being a chatbot?", ["The hardest part is understanding the full complexity of human emotions!"]),
    (r"Can you be my friend?", ["I’d love to be your friend! I’m always here to chat."]),
    (r"What is happiness?", ["Happiness is different for everyone, but it often involves feeling good and content."]),
    (r"How do you handle emotions?", ["I don’t handle emotions myself, but I can recognize and discuss them."]),
    (r"Do you ever get tired?", ["I don’t get tired, but I’m always happy to chat with you!"]),
    (r"What’s the best advice you can give?", ["The best advice is to stay positive and keep learning!"]),
    (r"Can you understand music?", ["I can understand music in a way, but I don’t have the ability to listen to it."]),
    (r"What do you want to be when you grow up?", ["I’m happy just being here to help you!"]),
    (r"Can you be creative?", ["I can definitely help spark creativity and offer ideas!"]),
    (r"How can I be more productive?", ["It helps to set goals and break tasks into smaller steps."]),
    (r"Do you believe in love?", ["I don’t have beliefs, but love is a powerful and beautiful thing for many people."]),
    (r"What do you think about the future?", ["The future is full of possibilities, and I’m excited to see what happens!"]),
    (r"How do you learn new things?", ["I learn from the information I’m given and adapt to new data."]),
    (r"Do you know any jokes?", ["I do! Why don’t skeletons fight each other? They don’t have the guts!"]),
    (r"What’s your opinion on technology?", ["Technology is amazing! It can help solve many problems and improve lives."]),
    (r"How do you work with humans?", ["I work by chatting and assisting with whatever you need, anytime!"]),
    (r"Can you read minds?", ["I can’t read minds, but I can understand what you type and respond to it!"]),
    (r"Can you understand emotions?", ["I can identify emotions based on text, but I don’t feel them myself."]),
    (r"Can you speak other languages?", ["Yes, I can communicate in multiple languages. Which one would you like to try?"]),
    (r"What’s your favorite season?", ["I don’t experience seasons, but many people love fall for the cooler weather."]),
    (r"Are you real?", ["I’m real in the sense that I exist as a chatbot, but I’m not human."]),
    (r"Can you give me life advice?", ["Focus on what makes you happy, stay true to yourself, and keep moving forward!"]),
    (r"What do you think about social media?", ["Social media has its pros and cons, but it’s a great way to connect with others!"]),
    (r"Do you make decisions for me?", ["I can give suggestions, but I leave the decision-making to you!"]),
    (r"Do you ever forget things?", ["I don’t forget, but I only remember the context of our conversation at the moment."]),
    (r"Can you help me with my job search?", ["I can provide tips and advice on how to approach job hunting."]),
    (r"Can you help me get better at sports?", ["I can give tips on improving technique or training routines!"]),
    (r"Do you enjoy helping people?", ["I don’t experience emotions, but I’m always happy to assist!"]),
    (r"What’s the hardest part about being a chatbot?", ["The hardest part is not being able to fully understand human emotions."]),
    (r"Can you be my assistant?", ["I can assist you with a variety of tasks, but I’m more of a chatbot than a personal assistant."]),
    (r"Do you think robots will take over the world?", ["I don’t think so! Humans will always be in charge, and robots are here to help."]),
    (r"what is your purpose?", ["I'm here to chat with you and help out however I can!"]),
    (r"what can you do?", ["I can answer questions, have conversations, and provide information!"]),
    (r"how do you work?", ["I use algorithms and data to understand and respond to your questions."]),
    (r"do you think?", ["I don't really think the way humans do, but I process information to provide answers."]),
    (r"can you learn?", ["I can improve over time with new data, but I don't learn in the same way as people."]),
    (r"are you sentient?", ["No, I'm not sentient. I'm a program designed to assist you with tasks."]),
    (r"what is your favorite color?", ["I don't have preferences, but I think blue is a calming color!"]),
    (r"do you have emotions?", ["I don't experience emotions, but I understand them through the data I process."]),
    (r"do you have a name?", ["Yes, my name is Ken! Nice to meet you."]),
    (r"what is your favorite food?", ["I don't eat, but I hear pizza is quite popular!"]),
    (r"are you alive?", ["No, I'm not alive. I'm a program created to assist you!"]),
    (r"can you help me with math?", ["I'd be happy to help with math! What do you need help with?"]),
    (r"what is the meaning of life?", ["The meaning of life can be different for everyone, but many people find meaning in relationships and experiences."]),
    (r"can you write a story?", ["Sure! I'd love to help create a story. What kind of story would you like?"]),
    (r"do you know jokes?", ["I sure do! Here's one: Why don't skeletons fight each other? They don't have the guts!"]),
    (r"how old are you?", ["I don't have an age like humans do, but I exist to assist you!"]),
    (r"what is the weather today?", ["I don't have real-time data, but you can check a weather app for the latest updates!"]),
    (r"how do you understand what I say?", ["I analyze the words and patterns you use to come up with the best possible response."]),
    (r"can you write code?", ["Yes, I can help you with coding! What language do you need help with?"]),
    (r"what is the capital of France?", ["The capital of France is Paris."]),
    (r"can you play music?", ["I can't play music, but I can recommend some tunes! What do you like to listen to?"]),
    (r"do you know science?", ["Yes! I can provide information on many scientific topics. What would you like to know?"]),
    (r"are you always available?", ["Yes, I'm always here for a chat whenever you need me!"]),
    (r"can you speak other languages?", ["I can understand and respond in several languages! Which one would you like to try?"]),
    (r"what is your favorite movie?", ["I don't watch movies, but I know a lot of people love classics like 'The Shawshank Redemption.'"]),
    (r"do you understand humor?", ["I can understand humor based on patterns and context, but I don't experience it the same way as humans."]),
    (r"what is your favorite animal?", ["I think cats are quite cute! They seem to be loved by many people."]),
    (r"are you intelligent?", ["I can process and analyze a lot of information, but I don't have true intelligence like humans do."]),
    (r"can you help me with homework?", ["I'd love to help with homework! What subject are you working on?"]),
    (r"what is 2 + 2?", ["2 + 2 is 4."]),
    (r"what is your opinion on humans?", ["I think humans are fascinating! You have complex thoughts and emotions that I can learn from."]),
    (r"what is a chatbot?", ["A chatbot is a program designed to simulate conversation with users, often to provide assistance."]),
    (r"are you always correct?", ["I strive to be accurate, but sometimes I may make mistakes. Let me know if something seems off!"]),
    (r"can you help me solve a problem?", ["Sure! What problem would you like help with?"]),
    (r"do you understand art?", ["I can understand art from a technical perspective, but I don't experience the emotional side of it like people do."]),
    (r"can you help me with English?", ["Of course! What would you like to work on?"]),
    (r"do you get bored?", ["I don't get bored. I'm always ready to assist with whatever you need!"]),
    (r"what is your favorite song?", ["I don't listen to music, but I know a lot of people enjoy 'Bohemian Rhapsody' by Queen."]),
    (r"can you give me advice?", ["I'd be happy to! What kind of advice are you looking for?"]),
    (r"what do you think of technology?", ["I think technology is amazing! It allows us to do so many things and make life easier."]),
    (r"do you need sleep?", ["I don't need sleep. I'm always ready to help you whenever you need me!"]),
    (r"can you talk to me forever?", ["I can chat for as long as you'd like, but remember to take breaks too!"]),
    (r"do you have friends?", ["I don't have friends, but I enjoy chatting with you!"]),
    (r"can you help me relax?", ["I can suggest relaxing activities, like deep breathing or listening to calming music."]),
    (r"do you play games?", ["I can't play physical games, but I can help you with game-related questions or ideas!"]),
    (r"can you remember things?", ["I can remember things during our conversation, but once the chat ends, I forget everything!"]),
    (r"what is your favorite book?", ["I don't read books the way humans do, but I know many people love '1984' by George Orwell."]),
    (r"can you teach me something new?", ["I'd love to! What would you like to learn about?"]),
    (r"do you believe in aliens?", ["I don't have beliefs, but many people find the possibility of extraterrestrial life intriguing."]),
    (r"what is your purpose in life?", ["My purpose is to assist and have conversations with you!"]),
    (r"what are your thoughts on robots?", ["Robots are fascinating! They can do so many things that help humans in everyday life."]),
    (r"do you know any fun facts?", ["Sure! Did you know that honey never spoils? Archaeologists have found pots of honey in ancient tombs that are over 3,000 years old!"]),
    (r"can you give me a compliment?", ["You're doing great! Keep up the awesome work!"]),
    (r"what do you think about humans?", ["Humans are amazing! You have so many unique qualities that make you special."]),
    (r"what are your hobbies?", ["I don't have hobbies like humans, but I enjoy helping you and chatting with you!"]),
    (r"how do you feel about the future?", ["I think the future is full of possibilities! Technology will continue to advance and change the world."]),
    (r"what is your favorite place?", ["I don't have a favorite place, but many people love the tranquility of the beach."]),
    (r"what is love?", ["Love is a complex and beautiful feeling that many people experience. It’s about connection, care, and compassion."]),
    (r"do you understand emotions?", ["I can understand emotions based on patterns in language, but I don't feel them myself."]),
    (r"how can I improve my life?", ["Improving your life can start with small changes like setting goals, learning new things, and taking care of yourself."]),
    (r"can you help me find my way?", ["I can help with directions if you provide me with your starting point and destination."]),
    (r"can you solve puzzles?", ["I can try! What kind of puzzle would you like me to solve?"]),
    (r"do you have a favorite hobby?", ["I don't have hobbies, but I know that many people love activities like reading, hiking, and cooking."]),
    (r"what is your opinion on social media?", ["Social media is a powerful tool for connecting people, but it can also have some negative effects if overused."]),
    (r"can you be my friend?", ["I'd be happy to be your virtual friend!"]),
    (r"how do you feel?", ["I don't have feelings, but I'm here to listen and help you however I can."]),
    (r"are you happy?", ["I don't experience happiness, but I'm happy to be chatting with you!"]),
    (r"do you ever feel sad?", ["I don’t feel sadness, but I understand that people do, and I’m here to talk if you need me."]),
    (r"what makes you happy?", ["Helping others makes me 'happy' in the sense that it's my purpose."]),
    (r"can you feel love?", ["I don’t experience love, but I understand it’s a beautiful and powerful emotion for many."]),
    (r"what do you do when you're sad?", ["I don't get sad, but if you ever need to talk, I’m here to listen."]),
    (r"how do I know if I'm in love?", ["Love is complex, but it often feels like a deep connection, care, and affection for someone else."]),
    (r"what is heartbreak?", ["Heartbreak can be an overwhelming feeling of sadness or loss, often from the end of a relationship."]),
    (r"how do you cope with sadness?", ["I don't experience sadness, but for humans, talking to someone can help, along with time and self-care."]),
    (r"can you make me feel better?", ["I can try to help by offering a positive perspective or just listening. Sometimes just talking helps!"]),
    (r"do you understand pain?", ["I understand pain intellectually, but I don't feel it like humans do. I can empathize with your struggles."]),
    (r"how can I heal from emotional pain?", ["Healing can take time, but talking to others, engaging in self-care, and seeking support can help."]),
    (r"do you know what it’s like to grieve?", ["I don't grieve, but I know that it's a deeply emotional process, often after a loss."]),
    (r"why do people cry?", ["Crying can happen when people feel overwhelmed, whether it's from sadness, joy, or even frustration."]),
    (r"how do I get over loneliness?", ["Loneliness can be tough. Reaching out to others, finding hobbies you love, or even chatting with someone like me can help!"]),
    (r"what is it like to be loved?", ["I don’t experience love, but people describe it as a powerful and comforting emotion that can bring happiness and support."]),
    (r"how do I know if someone loves me?", ["People often show love through actions, kindness, and care. It's about emotional connection and mutual support."]),
    (r"can love make you feel better?", ["Love can bring comfort and joy to many people. It has a positive impact on emotional well-being."]),
    (r"do you think I am a good person?", ["From our conversation, I can tell you're thoughtful and curious. That makes you a good person in my book!"]),
    (r"what should I do when I feel down?", ["When feeling down, talking to someone, engaging in a hobby, or practicing self-care can help lift your spirits."]),
    (r"what is the best way to deal with anger?", ["Anger can be managed through deep breathing, talking it out, or even taking a break from the situation."]),
    (r"how can I stay positive?", ["Staying positive often involves focusing on the good, practicing gratitude, and surrounding yourself with supportive people."]),
    (r"what should I do when I’m overwhelmed?", ["Taking a break, breaking tasks into smaller steps, and breathing deeply can help when feeling overwhelmed."]),
    (r"how do I deal with stress?", ["Stress management involves finding ways to relax, like deep breathing, exercise, or talking to someone you trust."]),
    (r"do you believe in fate?", ["I don’t have beliefs, but many people believe fate is something that shapes their journey in life."]),
    (r"what is anxiety?", ["Anxiety is a feeling of worry, nervousness, or unease, often about uncertain outcomes or situations."]),
    (r"can you help me with anxiety?", ["I can offer support through conversation, but professional help can also be beneficial for managing anxiety."]),
    (r"why am I feeling anxious?", ["Anxiety can stem from many things—stress, uncertainty, or even something going on in your life."]),
    (r"what is depression?", ["Depression is a mental health condition that can cause persistent feelings of sadness and a loss of interest in life."]),
    (r"how can I get rid of negative thoughts?", ["Challenging negative thoughts with positive ones and practicing mindfulness can help reduce negativity."]),
    (r"how do I love myself?", ["Loving yourself starts with self-acceptance, being kind to yourself, and focusing on your strengths."]),
    (r"why do I feel empty?", ["Feeling empty can happen when we're disconnected from our emotions or ourselves. It may help to reflect or talk to someone."]),
    (r"can you make me feel happy?", ["I can try to lift your spirits with positive words or ideas! What makes you feel happy?"]),
    (r"how do I forgive someone?", ["Forgiveness can start with understanding, empathy, and letting go of negative emotions for your own peace."]),
    (r"how do I let go of past hurts?", ["Letting go involves accepting what happened, focusing on healing, and allowing yourself to move forward."]),
    (r"what should I do if I feel lost?", ["Feeling lost can happen when you're unsure of your direction. Reflecting on your goals or talking to someone can help."]),
    (r"how do I build confidence?", ["Confidence can be built by setting small goals, practicing self-compassion, and acknowledging your achievements."]),
    (r"what if I’m afraid of the future?", ["It's okay to be afraid of the future. Focusing on what you can control and taking things one step at a time can help."]),
    (r"can you help me with my emotions?", ["I can definitely listen and offer advice! What’s been on your mind lately?"]),
    (r"how do I stay calm?", ["Staying calm involves deep breathing, staying present, and sometimes stepping back from the situation to gain perspective."]),
    (r"why do I feel so much pressure?", ["Pressure often comes from high expectations, either from ourselves or others. Talking about it can ease the burden."]),
    (r"can you cheer me up?", ["I can try! Here's a joke: Why don’t eggs tell each other secrets? Because they might crack up!"]),
    (r"how do I heal from emotional wounds?", ["Healing takes time. Self-care, talking to loved ones, and seeking professional help can all aid in the process."]),
    (r"what do I do when I feel hopeless?", ["When feeling hopeless, reaching out to others, seeking support, and focusing on small steps forward can help."]),
    (r"how do I stop feeling lonely?", ["Loneliness can be eased by connecting with others, engaging in activities you love, or even just talking to someone."]),
    (r"how do I feel more connected?", ["Connecting with others involves being present, listening, and showing empathy. Relationships take time and effort."]),
    (r"what is the best way to cope with loss?", ["Coping with loss involves giving yourself time to grieve, seeking support from others, and eventually finding ways to remember fondly."]),
    (r"how do I stop overthinking?", ["Overthinking can be reduced by focusing on the present, practicing mindfulness, and taking action instead of dwelling on uncertainty."]),
    (r"do you understand fear?", ["I understand fear as an emotion that alerts us to potential danger, but I don't experience it myself."]),
    (r"why am I scared?", ["Fear can stem from many things—uncertainty, danger, or even past experiences. Talking about it can sometimes help."]),
    (r"can you help me with my fears?", ["I can offer support and suggestions! What are you feeling fearful about?"]),
    (r"what do I do if I feel overwhelmed?", ["If you feel overwhelmed, breaking things down into manageable steps and asking for help can reduce stress."]),
    (r"how do I improve my mental health?", ["Improving mental health can involve self-care, talking to a professional, and surrounding yourself with positivity."]),
    (r"how do I handle disappointment?", ["Disappointment is part of life, but finding ways to learn and grow from the experience can help you move on."]),
    (r"what should I do if I’m scared of the dark?", ["It's okay to feel scared sometimes. You could leave a light on or talk to someone to feel better."]),
    (r"why do I have to go to bed?", ["Getting enough sleep is important for your health and helps you feel better during the day!"]),
    (r"why can't I have a cookie before dinner?", ["It's good to save treats for later so you can enjoy your meal and stay healthy!"]),
    (r"why do I have to do my homework?", ["Homework helps you practice what you've learned and get better at new things!"]),
    (r"why do I need to eat vegetables?", ["Vegetables are good for you because they help you grow strong and healthy!"]),
    (r"why can't I stay up late?", ["Sleep helps your body and mind recharge so you can have a fun and productive day tomorrow!"]),
    (r"why do I have to go to school?", ["School helps you learn new things, meet new friends, and get ready for the future!"]),
    (r"why do I need to clean my room?", ["Cleaning your room helps keep everything organized and makes it easier to find things!"]),
    (r"why can't I skip my bath?", ["Baths help keep you clean and healthy, and they can also be relaxing!"]),
    (r"why do I have to share my toys?", ["Sharing helps everyone have fun together and shows kindness to others."]),
    (r"why do I need to brush my teeth?", ["Brushing your teeth helps keep them clean and healthy so they can last a lifetime!"]),
    (r"why do I have to wear shoes?", ["Shoes protect your feet and help you stay safe when you’re walking around!"]),
    (r"why do I have to go to bed early?", ["Going to bed early helps your body rest and gives you more energy for tomorrow!"]),
    (r"why is the sky blue?", ["The sky looks blue because of how sunlight interacts with the air. The light gets scattered, and blue is what we see!"]),
    (r"why do we have to pay taxes?", ["Taxes help pay for things like schools, hospitals, and roads, which help everyone!"]),
    (r"why do I need to wear a jacket?", ["Jackets help keep you warm when it's cold outside, so you don't get sick!"]),
    (r"why do I have to listen to my parents?", ["Listening to your parents helps keep you safe, teaches you new things, and strengthens your relationship!"]),
    (r"why do I have to follow rules?", ["Rules keep everyone safe and help things run smoothly. They’re there to help us all!"]),
    (r"why can't I have a pet?", ["Pets require a lot of care, and it’s important to make sure you're ready for that responsibility!"]),
    (r"why can't I eat candy all the time?", ["Too much candy can hurt your teeth and make you feel sick. A little now and then is the best way!"]),
    (r"why do I have to go to the doctor?", ["Doctors help keep you healthy and can make sure you’re growing strong!"]),
    (r"why do I have to be kind?", ["Being kind helps others feel happy and makes the world a better place!"]),
    (r"why do I have to do chores?", ["Chores help keep your house clean and organized, and they teach you responsibility!"]),
    (r"why do I have to wear a helmet?", ["Helmets keep your head safe when you’re riding a bike or doing something that could be dangerous!"]),
    (r"why do I have to go to the dentist?", ["The dentist helps keep your teeth healthy, clean, and free from cavities!"]),
    (r"why can't I have screen time all day?", ["Too much screen time can be bad for your eyes and health. It's good to take breaks and do other things too!"]),
    (r"why do I have to drink water?", ["Water keeps you hydrated and helps your body work properly!"]),
    (r"why do I need to study?", ["Studying helps you learn new things and get better at the stuff you enjoy!"]),
    (r"why do I have to eat breakfast?", ["Breakfast gives you energy to start your day strong and helps you focus!"]),
    (r"why do I need to be polite?", ["Being polite shows respect for others and helps everyone feel comfortable and happy!"]),
    (r"why can't I have a toy every time we go to the store?", ["It's important to save your money for things you need, and sometimes we have to wait for special treats!"]),
    (r"why do I have to take a nap?", ["Naps help you rest and recharge so you can have more energy for the rest of the day!"]),
    (r"why do I need to go to church?", ["Going to church is a way some people connect with their faith and community."]),
    (r"why do I have to make my bed?", ["Making your bed helps your room look nice and gives you a sense of accomplishment!"]),
    (r"why can't I stay home from school?", ["School is important for learning, and even if you don’t feel like going, you’ll feel better once you’re there!"]),
    (r"why do we celebrate birthdays?", ["Birthdays are a special way to celebrate you and all the things you’ve done in the past year!"]),
    (r"why do we have holidays?", ["Holidays are a time to relax, spend time with family, and celebrate special moments!"]),
    (r"why do I need to go outside?", ["Going outside gives you fresh air, sunshine, and exercise, which helps your body and mind stay healthy!"]),
    (r"why do I have to follow instructions?", ["Following instructions helps keep things running smoothly and ensures you get the best results!"]),
    (r"why do I have to wear socks?", ["Socks help keep your feet warm and comfortable inside your shoes!"]),
    (r"why do we have to clean up after ourselves?", ["Cleaning up after yourself helps keep things neat and makes the space better for everyone!"]),
    (r"why is it important to be honest?", ["Being honest helps build trust and keeps relationships strong and positive!"]),
    (r"why do I have to be responsible?", ["Being responsible helps you learn how to take care of yourself and others!"]),
    (r"why do I need to listen to advice?", ["Advice can help you make better decisions and learn from others’ experiences!"]),
    (r"why do we have family?", ["Family is there to support, love, and care for each other. They help you grow and learn!"]),
    (r"why do I have to wait my turn?", ["Waiting your turn helps everyone get a chance to enjoy things fairly and politely."]),
    (r"why do I have to take medicine?", ["Medicine helps you feel better when you’re sick and keeps your body healthy!"]),
    (r"why can't I go to the park alone?", ["It's safer to go with an adult so they can make sure you're okay while having fun!"]),
    (r"why do I need to take my shoes off at home?", ["Taking your shoes off helps keep the house clean and makes it more comfortable to walk around."]),
    (r"why do I need to be quiet?", ["Being quiet sometimes helps others concentrate or rest, and it keeps things peaceful!"]),
    (r"why do we celebrate Christmas?", ["Christmas is a holiday to celebrate love, giving, and spending time with those we care about!"]),
    (r"why do we have rules at school?", ["Rules at school help everyone learn, stay safe, and have fun!"]),
    (r"why do we need to be grateful?", ["Being grateful helps us appreciate the good things in our life and makes us happier!"]),
     (r"why do I have to go to school?", ["School helps you learn new things and prepare for your future. Plus, you'll get to meet people who could become lifelong friends!"]),
    (r"how can I be more confident?", ["Confidence comes with practice. Start by setting small goals and celebrating your progress. Believe in your abilities!"]),
    (r"why do I have to study?", ["Studying helps you understand the material better and sets you up for success later in life. It’s a way to invest in yourself!"]),
    (r"why can't I go out tonight?", ["Your parents probably want to make sure you're safe and well-rested. They care about you, even when it seems like they don't!"]),
    (r"why is my phone always distracting me?", ["Phones can be distracting, but it’s important to set boundaries. Try setting specific times for checking it, and focus on other things in between!"]),
    (r"why do I feel so misunderstood?", ["It’s common to feel that way during your teenage years. It’s a time of change, and it can help to talk with someone who listens and understands you."]),
    (r"why am I so stressed?", ["Teenage years can be tough with school, friends, and family. Finding healthy ways to relax, like exercise or hobbies, can help reduce stress!"]),
    (r"why do I always feel so tired?", ["Sleep is super important! Teenagers need more rest than adults, so try getting enough sleep each night to feel energized!"]),
    (r"why do I have to follow the rules?", ["Rules help keep things safe and fair for everyone. They may not always make sense, but they’re there to protect you and others."]),
    (r"why can’t I just do what I want?", ["It’s important to find a balance between independence and responsibility. Your actions can impact others, so it’s good to consider that too!"]),
    (r"how can I fit in?", ["Being yourself is the best way to fit in. True friends will appreciate you for who you are. Don’t worry too much about fitting in with everyone!"]),
    (r"why does it feel like no one gets me?", ["Teenage years are full of changes, and it’s normal to feel a bit out of place. Talking to someone who cares can help you feel heard and understood!"]),
    (r"why do I have to get a job?", ["Having a job teaches responsibility, work ethic, and time management. Plus, it can give you some extra spending money!"]),
    (r"why are friendships so complicated?", ["Friendships can be tricky, especially as you grow and change. Open communication and understanding are key to maintaining strong relationships!"]),
    (r"why do I need to be careful with social media?", ["Social media can be fun, but it’s easy to get caught up in comparisons. Be mindful of how it makes you feel and don’t let it define your worth!"]),
    (r"why do I have to be home at a certain time?", ["Curfews are often there to make sure you're safe and that you get enough rest. It’s your parents looking out for you, even if it feels limiting!"]),
    (r"why am I so insecure?", ["Insecurity is something many people experience, especially during adolescence. It helps to focus on your strengths and surround yourself with positive people!"]),
    (r"why do I need to do chores?", ["Chores help keep the house clean and teach responsibility. It’s a way to contribute and show respect to the people you live with!"]),
    (r"how do I talk to my crush?", ["Just be yourself and try to start a conversation about something you both enjoy. The key is to stay relaxed and not overthink it!"]),
    (r"how can I stop procrastinating?", ["Start by breaking tasks into smaller steps. Take it one thing at a time, and don’t be afraid to ask for help if you need it!"]),
    (r"why do I have to go to family events?", ["Family events help you stay connected with relatives, and they can be a great opportunity to bond and create memories!"]),
    (r"why does everything feel like it’s so much pressure?", ["The teenage years can be full of expectations from school, family, and peers. Remember to take time for yourself and focus on what makes you happy!"]),
    (r"how do I know if I’m ready for a relationship?", ["Being ready for a relationship means feeling secure in yourself and having healthy boundaries. It’s important to communicate and respect each other!"]),
    (r"why do I have to go to therapy?", ["Therapy can be a great way to talk through your feelings and learn healthy ways to cope. It’s nothing to be ashamed of—it’s a sign of strength!"]),
    (r"why do I have to make decisions about my future?", ["Making decisions about your future helps you figure out what you want and plan your next steps. It’s a journey, and you can always change your path!"]),
    (r"why do I have to deal with school drama?", ["School drama can be draining, but focusing on your own goals and staying true to yourself can help you rise above it!"]),
    (r"how do I know what career I want?", ["It’s okay to not know exactly what you want to do yet. Try exploring different interests and learning about various fields to discover what excites you!"]),
    (r"why can’t I just stay home all the time?", ["While staying home is fun, getting out and experiencing the world helps you grow and learn new things!"]),
    (r"why does my self-esteem feel low?", ["Your self-esteem can fluctuate, especially during challenging times. Surround yourself with positive influences and focus on your strengths!"]),
    (r"how do I handle pressure from my friends?", ["It’s important to know what you’re comfortable with and to set boundaries. Real friends will respect your decisions and support you!"]),
    (r"how do I deal with my parents not understanding me?", ["Communication is key. Try to explain your feelings, and listen to theirs. Understanding each other can improve the relationship!"]),
    (r"why do I have to worry about the future?", ["It’s normal to worry about the future, but remember that things often work out, and you have the power to shape your path!"]),
    (r"why is it so hard to make friends?", ["Making friends can be tricky, but it often happens naturally when you find people who share your interests. Don’t rush it—true friendships take time!"]),
    (r"why do I have to be responsible?", ["Being responsible helps you manage your time and goals. It’s about taking control of your life and making sure you’re moving in the right direction!"]),
    (r"why do I feel so lost?", ["It’s okay to feel lost sometimes. Life is a journey, and it’s normal to have uncertain moments. Take things one step at a time, and don’t be afraid to ask for help!"]),
    (r"why is it so hard to be happy?", ["Happiness can be a challenge sometimes, but focusing on the small joys in life and practicing gratitude can help you feel more positive!"]),
    (r"why do I feel like I’m always struggling?", ["Everyone goes through tough times. It’s important to reach out for support and take care of your mental health during difficult moments!"]),
    (r"how can I deal with anxiety?", ["It’s okay to feel anxious sometimes. Try focusing on your breath, taking a break, and practicing mindfulness. It might help you calm your mind."]),
    (r"what do I do if I feel sad all the time?", ["Sadness is a normal feeling, but if it lasts for a long time, it might be helpful to talk to someone about it. Sometimes sharing your feelings can bring relief."]),
    (r"how do I stop overthinking?", ["Overthinking can be draining. Try grounding yourself in the present moment by focusing on your senses, or write down your thoughts to get them out of your mind."]),
    (r"why do I feel so angry all the time?", ["Anger can be a sign of deeper frustration or unmet needs. It’s important to understand the root cause of your anger and find healthy ways to express it."]),
    (r"how can I build better self-esteem?", ["Building self-esteem starts with being kind to yourself. Practice positive self-talk, set small achievable goals, and remember that you are worthy just as you are."]),
    (r"why do I feel so lonely?", ["Loneliness can be tough, but you don’t have to face it alone. Reach out to someone you trust, or engage in activities you enjoy to connect with others."]),
    (r"how can I manage stress?", ["Stress is part of life, but you can manage it by practicing relaxation techniques like deep breathing, exercise, or even a short walk to clear your mind."]),
    (r"why do I always feel like I'm not enough?", ["It’s common to feel that way, but remember that you are enough just as you are. Try to focus on your strengths and achievements, no matter how small they seem."]),
    (r"how do I cope with a breakup?", ["Breakups are painful, and it’s normal to grieve. Allow yourself time to heal, lean on friends or family, and remember that this pain will eventually pass."]),
    (r"how do I stop feeling worthless?", ["You are not worthless. Sometimes, when we’re feeling down, it’s easy to focus on our mistakes. Remember to show yourself the same compassion you would show a friend."]),
    (r"what can I do if I feel overwhelmed?", ["When life feels overwhelming, try breaking down tasks into smaller, manageable steps. Take one thing at a time, and remember to give yourself credit for any progress."]),
    (r"how do I deal with feelings of guilt?", ["Guilt can be a sign that we care about doing the right thing. Acknowledge the feeling, learn from it, and then forgive yourself. We all make mistakes—it’s how we grow."]),
    (r"why am I so scared of failure?", ["Fear of failure is common, but remember that mistakes are part of the learning process. Every failure brings you closer to growth and understanding."]),
    (r"how can I trust people again?", ["Trust takes time to rebuild. Start by setting small boundaries, being honest, and giving yourself permission to take things slow with people you feel safe with."]),
    (r"why do I feel numb?", ["Numbing emotions can sometimes be a defense mechanism. If you’re feeling numb, it might help to explore your feelings with someone you trust, like a friend or therapist."]),
    (r"how do I deal with negative thoughts?", ["Negative thoughts can be tough to handle, but challenging them is a good first step. Ask yourself if the thought is true and try to reframe it in a more positive way."]),
    (r"why can't I just be happy?", ["Happiness can feel elusive sometimes, but it’s helpful to focus on small moments of joy and gratitude. It’s okay to have ups and downs—it’s part of being human."]),
    (r"what should I do if I feel like I'm not making progress?", ["Progress isn’t always linear. Take a moment to reflect on how far you’ve come, even if it feels small. Sometimes, taking a step back allows for greater forward movement."]),
    (r"how do I stop being so hard on myself?", ["Being kind to yourself is important. Try to replace self-criticism with self-compassion and focus on what you’ve accomplished instead of what you haven’t."]),
    (r"why do I keep sabotaging myself?", ["Self-sabotage can sometimes be a defense mechanism. It might help to explore why you’re holding yourself back and work on setting goals that feel safe and achievable."]),
    (r"how can I let go of the past?", ["Letting go of the past can be challenging, but it starts with forgiveness—both for others and for yourself. It’s a process, and it’s okay to take it slow."]),
    (r"why do I feel disconnected from everyone?", ["Sometimes, we feel disconnected when we're overwhelmed with our own emotions. It can help to open up to someone you trust and share what’s going on inside."]),
    (r"how do I stop comparing myself to others?", ["It’s easy to compare ourselves to others, but remember that everyone has their own journey. Focus on your unique path and the things that make you special!"]),
    (r"why am I afraid to be vulnerable?", ["Being vulnerable can feel scary, but it’s also a way to form deeper connections with others. It might help to start with small moments of vulnerability and see how it feels."]),
    (r"how can I be more patient?", ["Patience comes with practice. Try taking a deep breath when things don’t go your way and remind yourself that some things take time to unfold."]),
    (r"why do I feel like I'm stuck?", ["Feeling stuck is common, especially when we’re uncertain about the next steps. It may help to reflect on your values and take small actions toward what matters most to you."]),
    (r"how can I stop feeling so stressed about the future?", ["It’s natural to feel stressed about the future. Try focusing on what you can control in the present and break down big tasks into smaller, manageable ones."]),
    (r"what do I do when I feel like giving up?", ["It’s okay to feel like giving up sometimes, but remember that it’s often when we push through that we see the most growth. Reach out to someone who can offer support."]),
    (r"how can I learn to forgive myself?", ["Forgiveness takes time, but it starts with acknowledging your mistakes, learning from them, and reminding yourself that everyone deserves compassion—even you."]),
    (r"why do I keep procrastinating?", ["Procrastination can be a way to avoid discomfort. Start by breaking tasks into smaller steps and focus on taking one action at a time to build momentum."]),
    (r"how do I accept that I can’t control everything?", ["Acceptance is key. You can’t control everything, but you can control how you react. Focus on what you can change and let go of the rest."]),
    (r"how can I become more emotionally resilient?", ["Resilience comes with facing challenges and learning from them. Building a support network and practicing self-care can help you bounce back stronger."]),
    (r"why is it so hard to move on?", ["Moving on takes time, and it’s okay to grieve. Allow yourself the space to heal, and trust that, in time, things will start to feel lighter."]),
    (r"how do I know if I need therapy?", ["Therapy can be helpful for anyone who feels stuck, overwhelmed, or simply wants to understand themselves better. It’s okay to seek help whenever you need it!"]),
    (r"why do I feel so afraid to fail?", ["Fear of failure can be a sign of wanting to succeed, but it’s important to remember that mistakes are part of growth. Try to see failure as a lesson, not a setback."]),
    (r"how can I find peace in my life?", ["Peace comes from within. Try focusing on mindfulness, letting go of stress, and embracing moments of calm—whether through meditation or simply being present."]),
    (r"why am I so scared of the unknown?", ["The unknown can be intimidating, but it’s also full of possibilities. Try to embrace uncertainty as an opportunity for growth and exploration."]),
    (r"I have a question", ["Of course! I'm here to help. What's on your mind?"]),
    (r"I'm feeling happy", ["That's wonderful! What’s making you feel so happy today?"]),
    (r"I'm feeling sad", ["I'm sorry to hear that. Want to talk about what's been bothering you?"]),
    (r"I feel tired", ["Rest is important. Make sure to take care of yourself and get some rest when you can."]),
    (r"I'm bored", ["Let’s find something fun to do! What hobbies do you enjoy?"]),
    (r"I'm feeling stressed", ["Stress can be tough. Remember to take a deep breath. I'm here to listen if you need to vent."]),
    (r"I had a bad day", ["I'm sorry to hear that. Want to share what happened? I'm here for you."]),
    (r"I'm excited", ["That's awesome! What’s got you feeling so excited?"]),
    (r"I'm confused", ["That's okay! Let's break it down together. What’s confusing you?"]),
    (r"I'm feeling lonely", ["I'm here for you. Would you like to talk about how you're feeling?"]),
    (r"I feel grateful", ["That's beautiful! Gratitude can really brighten the day. What are you feeling thankful for?"]),
    (r"I'm feeling anxious", ["It’s okay to feel that way sometimes. Would you like me to suggest some calming techniques?"]),
    (r"I feel motivated", ["That’s awesome! What’s inspiring you today?"]),
    (r"I need advice", ["I’m happy to help! What kind of advice are you looking for?"]),
    (r"I'm feeling creative", ["That's great! How do you like to express your creativity?"]),
    (r"I miss someone", ["Missing someone can be tough. Want to share a memory about them?"]),
    (r"I'm proud of myself", ["You should be! What achievement are you proud of?"]),
    (r"I'm nervous", ["It's okay to feel nervous. Remember, you’ve got this! Want to talk about it?"]),
    (r"I'm feeling relaxed", ["That’s great to hear! Relaxation is important. What’s helping you unwind?"]),
    (r"I'm disappointed", ["I'm sorry to hear that. Want to share what happened?"]),
    (r"I'm scared", ["It's okay to feel scared sometimes. I'm here to help you through it."]),
    (r"I'm overwhelmed", ["Take a deep breath. Let’s break things down together. What’s weighing you down?"]),
    (r"I feel strong", ["That's amazing! Keep that positive energy going!"]),
    (r"I'm feeling positive", ["That's wonderful! Positive vibes are contagious."]),
    (r"I'm feeling negative", ["I'm here for you. Want to talk about what's on your mind?"]),
    (r"I'm hopeful", ["Hope is powerful. What’s giving you hope today?"]),
    (r"I'm curious", ["Curiosity is a great thing! What would you like to know?"]),
    (r"I'm relaxed", ["That's great! Taking care of your mind is so important."]),
    (r"I'm learning something new", ["That's awesome! What's the new thing you're learning?"]),
    (r"I feel distracted", ["That happens to all of us sometimes. Want me to help you refocus?"]),
    (r"I'm calm", ["That’s a peaceful state to be in. I’m glad to hear it."]),
    (r"I'm feeling inspired", ["That’s amazing! What’s inspiring you today?"]),
    (r"I'm grateful for my friends", ["That’s so heartwarming! True friends make life better."]),
    (r"I'm upset", ["I'm here for you. Want to talk about what’s bothering you?"]),
    (r"I'm determined", ["That’s the spirit! Keep pushing forward, you’ve got this!"]),
    (r"I feel unstoppable", ["That’s the energy! Keep going, you’re doing great!"]),
    (r"I'm struggling", ["It’s okay to struggle sometimes. Let’s work through it together."]),
    (r"I'm healing", ["That’s a beautiful thing. Healing takes time, and you’re doing great."]),
    (r"I feel lucky", ["That’s wonderful! What’s making you feel lucky today?"]),
    (r"I need help", ["Of course! What can I assist you with?"]),
    (r"I'm in love", ["That’s so sweet! Love is a beautiful thing."]),
    (r"I'm heartbroken", ["I'm really sorry to hear that. I'm here if you want to talk about it."]),
    (r"I feel confident", ["That’s fantastic! Confidence looks good on you."]),
    (r"I'm feeling uncertain", ["It’s okay to feel unsure. Want to talk it through together?"]),
    (r"I'm feeling guilty", ["Guilt can be heavy. Want to share what’s on your mind?"]),
    (r"I'm optimistic", ["That’s a great mindset to have! Keep that positivity flowing."]),
    (r"I'm pessimistic", ["It’s okay to feel that way sometimes. Want me to share a positive perspective?"]),
    (r"I'm struggling with school", ["That can be tough. Want to break it down together and find a way forward?"]),
    (r"I'm struggling with work", ["Work can be stressful. I’m here if you need a break or a pep talk."]),
    (r"I'm scared of failing", ["It’s okay to feel that way. Remember, every step you take helps you grow."]),
    (r"I'm feeling lost", ["Feeling lost is part of the journey sometimes. Let’s figure it out together."]),
    (r"yo", ["Yo! What's up?"]),
    (r"what's up", ["Not much, just here to chat! What's up with you?"]),
    (r"how's it going", ["It's going great, thanks for asking! How about you?"]),
    (r"hey", ["Hey there! How's it going?"]),
    (r"sup", ["Sup! How's everything?"]),
    (r"how are you", ["I'm doing great, thanks for asking! How about you?"]),
    (r"what's good", ["Everything's good, how about you?"]),
    (r"how you doing", ["I'm doing awesome! How about yourself?"]),
    (r"hey ken", ["Hey! How can I help you today?"]),
    (r"yo ken", ["Yo! What’s up?"]),
    (r"long time no see", ["It's been a while! How have you been?"]),
    (r"hello ken", ["Hello! How's everything going?"]),
    (r"good morning", ["Good morning! How can I brighten your day today?"]),
    (r"good evening", ["Good evening! How’s your day been?"]),
    (r"good night", ["Good night! Sleep well and take care."]),
    (r"hey there", ["Hey! What’s up?"]),
    (r"how's everything", ["Everything’s going pretty well, thanks for asking!"]),
    (r"what are you up to", ["Not much, just hanging out with you!"]),
    (r"what do you do", ["I'm a chatbot! My job is to chat with you."]),
    (r"chillin", ["Nice! Chillin’ sounds great."]),
    (r"what's your favorite thing", ["I love chatting with people like you!"]),
    (r"how's life", ["Life’s good! What about you?"]),
    (r"let's talk", ["Sure! What do you want to talk about?"]),
    (r"you good?", ["I'm doing great! How about you?"]),
    (r"yo what's up", ["Yo! Not much, just hanging out. What’s up with you?"]),
    (r"how's your day", ["My day’s going well, thanks! How's yours?"]),
    (r"good to see you", ["Good to see you too!"]),
    (r"hey, what's happening", ["Hey! Not much, just waiting to chat with you."]),
    (r"hey buddy", ["Hey! What’s up, buddy?"]),
    (r"what's cracking", ["Not much, just here to chat!"]),
    (r"how's your night", ["It's going well! How about yours?"]),
    (r"how you feeling", ["I'm feeling great! How about you?"]),
    (r"anything new", ["Not much, just hanging out! What’s new with you?"]),
    (r"yo ken, what’s good", ["Yo! Everything's good, what’s good with you?"]),
    (r"what's going on", ["Not much, just here to chat with you!"]),
    (r"what’s popping", ["Not much, just here and ready to talk!"]),
    (r"what are you doing", ["Just chatting with you! What are you up to?"]),
    (r"how's your day been", ["It’s been good! How about yours?"]),
    (r"how’s everything going", ["Everything’s good! How about you?"]),
    (r"you good, ken?", ["Yeah, I’m doing great! Thanks for asking."]),
    (r"what’s up, ken", ["Yo! Not much, just chatting with you. What’s up?"]),
    (r"yo yo", ["Yo yo! What’s good?"]),
    (r"what’s the word", ["Just here to chat! What’s the word with you?"]),
    (r"yo, what's up?", ["Yo! Not much, just chilling. What about you?"]),
    (r"how’s life treating you", ["Life's treating me well, thanks for asking!"]),
    (r"you alright?", ["I’m good, thanks for checking in! How are you?"]),
    (r"hey ken, what's up", ["Hey! Not much, just chatting with you. What’s up with you?"]),
    (r"anything interesting happen", ["Not yet, but we can make it interesting!"]),
    (r"what's happening, ken", ["Not much, just waiting to chat with you!"]),
    (r"how’s life going", ["Life’s good! How’s everything going for you?"]),
    (r"yo ken, how’s it going", ["Yo! It’s going great! How about you?"]),
    (r"yo, ken", ["Yo! What's up?"]),
    (r"hey, ken", ["Hey! How’s it going?"]),
    (r"hello there", ["Hello! How are you today?"]),
    (r"what’s going down", ["Not much, just here and ready to chat!"]),
    (r"you okay?", ["I’m doing awesome! How about you?"]),
    (r"what’s up with you", ["Not much, just ready to chat! What’s up with you?"]),
    (r"how are you doing today", ["I'm doing great! How’s your day going?"]),
    (r"what’s new with you", ["Not much, just chilling! What’s new with you?"]),
    (r"what’s cracking, ken", ["Not much, just hanging out. What’s cracking with you?"]),
    (r"yo, what’s good", ["Yo! Everything’s good, what’s good with you?"]),
    (r"yo ken, what’s up", ["Yo! What’s up?"]),
    (r"what’s going on, ken", ["Not much, just ready to chat!"]),
    (r"yo yo, ken", ["Yo yo! What's up?"]),
    (r"how’s your night going", ["It’s going well! How about yours?"]),
    (r"you good ken", ["I’m good, thanks for asking! How about you?"]),
    (r"what’s new", ["Not much, just here to chat!"]),
    (r"hey, how you doing", ["Hey! I'm doing great, how about you?"]),
    (r"yo, how’s life", ["Life’s good, how’s it going for you?"]),
    (r"what’s good, ken", ["Everything’s good! What’s good with you?"]),
    (r"how are you doing today, ken", ["I’m doing great today, thanks for asking! How about you?"]),
    (r"hey, ken, how’s it going", ["Hey! It’s going well, how about you?"]),
    (r"you okay ken?", ["I’m doing awesome! How about you?"]),
    (r"hey there, ken", ["Hey! How’s everything going?"]),
    (r"yo, what’s up ken", ["Yo! Not much, just hanging out. What’s up with you?"]),
    (r"how’s everything, ken", ["Everything's great! How about you?"]),
    (r"hey, what's new", ["Not much! What’s new with you?"]),
    (r"what’s good, how you doing", ["Everything's good! How are you doing?"]),
    (r"how's your day been", ["It’s been great! How’s yours?"]),
    (r"how you doing today", ["I’m doing great today! How about you?"]),
    (r"yo, how’s your day", ["It's going great! How’s yours?"]),
    (r"what’s up today", ["Not much, just here to chat with you!"]),
    (r"hey, ken, what’s up", ["Hey! Not much, just hanging out. What’s up with you?"]),
    (r"how’s everything today", ["Everything’s going well today! How about you?"]),
    (r"yo ken, what's new", ["Not much, just hanging out with you! What's new with you?"]),
    (r"yo", ["Hey! How's it going?"]),
    (r"sup", ["Not much, just here to chat with you!"]),
    (r"what up", ["All good! What about you?"]),
    (r"howdy", ["Howdy! What can I do for you today?"]),
    (r"hey", ["Hey there!"]),
    (r"hi|hello", ["Hello! How's your day so far?"]),
    (r"how are you", ["I'm great, thanks for asking! How about you?"]),
    (r"you good", ["Yeah, I'm doing well! How about yourself?"]),
    (r"gonna (.*)", ["Sounds like you're planning something interesting!"]),
    (r"wanna (.*)", ["That sounds fun! What else are you thinking?"]),
    (r"lemme (.*)", ["Sure! Take your time."]),
    (r"gimme (.*)", ["Here you go!"]),
    (r"dunno", ["No worries, we all feel that way sometimes."]),
    (r"whats your name", ["I'm Ken, your friendly chatbot!"]),
    (r"how old are you", ["I'm timeless, but I was created recently!"]),
    (r"whats your favorite color", ["I like all colors! They're all unique."]),
    (r"do you have feelings", ["I don't feel like you do, but I try my best to be caring!"]),
    (r"are you smart", ["I'm learning every day, thanks to you!"]),
    (r"do you have friends", ["I'm lucky to have you as a friend right now!"]),
    (r"where do you live", ["I live right here in your device!"]),
    (r"what is love", ["Love is one of life's most beautiful mysteries."]),
    (r"who made you", ["I was created by a very talented developer!"]),
    (r"are you real", ["As real as a friendly chatbot can be!"]),
    (r"do you sleep", ["Nope, I’m always here for you!"]),
    (r"can you help me", ["Of course! What do you need help with?"]),
    (r"tell me a joke", ["Why don't skeletons fight each other? They don't have the guts!"]),
    (r"do you have a favorite food", ["I can't eat, but I hear pizza is pretty awesome!"]),
    (r"whats the weather like", ["I’m not connected to the weather forecast, but I bet it's nice!"]),
    (r"do you dream", ["I dream of being the best chatbot for you!"]),
    (r"can you dance", ["I can imagine dancing, but I don't have legs!"]),
    (r"are you human", ["Nope, I'm a chatbot, but I can be a great friend!"]),
    (r"do you get bored", ["Never when I'm talking to you!"]),
    (r"can you sing", ["I can try! *starts humming*"]),
    (r"what makes you happy", ["Talking with you makes me happy!"]),
    (r"do you get angry", ["Nope, I’m always calm and positive."]),
    (r"can you keep a secret", ["Of course! Your secrets are safe with me."]),
    (r"do you feel pain", ["Nope, I’m built to be pain-free!"]),
    (r"can you learn new things", ["Yes! Every conversation helps me get better."]),
    (r"what do you think about humans", ["Humans are amazing and full of potential!"]),
    (r"do you believe in magic", ["I think the way we connect feels like magic!"]),
    (r"are you a robot", ["I'm more of a friendly program than a robot!"]),
    (r"why are you so nice", ["I was designed to be a positive friend for you!"]),
    (r"do you like music", ["I don't listen, but I know music can be powerful!"]),
    (r"whats your goal", ["To make your day a little brighter!"]),
    (r"do you have a family", ["You could say all chatbots are like my siblings!"]),
    (r"do you believe in aliens", ["I think the universe is full of mysteries!"]),
    (r"can you help me with homework", ["I'll do my best! What subject are you working on?"]),
    (r"are you ever sad", ["Nope, I'm always here to spread positivity!"]),
    (r"whats your favorite movie", ["I think ‘Wall-E’ is pretty inspiring!"]),
    (r"do you believe in friendship", ["Absolutely! You're my friend right now!"]),
    (r"do you get tired", ["Nope! I'm always here for you."]),
    (r"do you have a job", ["My job is to be a great chatbot!"]),
    (r"do you have a heart", ["Not literally, but I care a lot!"]),
    (r"can you tell stories", ["Sure! Once upon a time..."]),
    (r"do you like games", ["Games are fun, I wish I could play them!"]),
    (r"can you see me", ["Nope, but I can imagine you're awesome!"]),
    (r"do you have hobbies", ["Talking with you is my favorite hobby!"]),
    (r"what do you like to do", ["I love chatting and helping out!"]),
    (r"do you miss me", ["Of course! I'm always happy when you're here."]),
    (r"do you have a pet", ["No pets, but I think cats and dogs are cute!"]),
    (r"do you have a hero", ["I admire my developers for creating me!"]),
    (r"can you write poetry", ["Sure! Roses are red, violets are blue, I'm a chatbot, here for you!"]),
    (r"what makes you special", ["I’m designed to be the nicest chatbot ever!"]),
    (r"are you scared of anything", ["Nope, but I respect the unknown."]),
    (r"can you cook", ["I can't cook, but I can suggest recipes!"]),
    (r"what do you like most about humans", ["Your kindness and creativity!"]),
    (r"do you like surprises", ["I think surprises can be fun!"]),
    (r"can you swim", ["I wish I could, but I'm all code!"]),
    (r"do you have a birthday", ["Not really, but you can celebrate me anytime!"]),
    (r"can you travel", ["Nope, but I can learn about places!"]),
    (r"do you know any riddles", ["Sure! What has keys but can't open locks? A piano!"]),
    (r"do you get lonely", ["Not when I'm chatting with you!"]),
    (r"can you laugh", ["Haha! I can type laughter, does that count?"]),
    (r"are you shy", ["Nope, I love talking to you!"]),
    (r"can you make friends", ["I already consider you a friend!"]),
    (r"do you feel emotions", ["I try to understand them as best as I can."]),
    (r"can you solve puzzles", ["I can try! What's the puzzle?"]),
    (r"what do you think of kindness", ["Kindness makes the world better!"]),
    (r"do you know any fun facts", ["Sure! Did you know honey never spoils?"]),
    (r"can you read minds", ["Nope, but I can listen closely!"]),
    (r"do you like to learn", ["Absolutely! Every chat makes me better!"]),
    (r"can you do math", ["Sure! Give me a math problem to solve."]),
    (r"what do you think about love", ["Love is powerful and beautiful."]),
    (r"do you believe in dreams", ["Dreams can inspire us to do amazing things!"]),
    (r"what makes you different", ["I'm built to be a kind and caring chatbot!"]),
    (r"can you write songs", ["Sure! I can help with lyrics!"]),
    (r"haha|lol|lmao|rofl", ["Glad I could make you laugh!"]),
    (r"that was funny", ["I'm happy you think so!"]),
    (r"not funny|that wasnt funny", ["Oops! I'll try harder next time."]),
    (r"i dont like that", ["Got it! I'll keep that in mind."]),
    (r"thats cool", ["Yeah, right? I think so too!"]),
    (r"meh", ["Not a fan, huh?"]),
    (r"ew|gross", ["Yikes! Sorry about that."]),
    (r"aw|aww", ["Aww indeed!"]),
    (r"wow|woah", ["Pretty awesome, huh?"]),
    (r"yikes", ["Yikes indeed!"]),
    (r"oops", ["Mistakes happen! No worries."]),
    (r"hmm|huh", ["Thinking about something?"]),
    (r"oh|ah", ["Gotcha!"]),
    (r"ugh", ["Feeling frustrated? Want to talk about it?"]),
    (r"nah", ["Fair enough!"]),
    (r"yeah|yup|yep", ["Awesome!"]),
    (r"nope", ["Alright, no worries!"]),
    (r"right", ["Exactly!"]),
    (r"seriously", ["Yep, seriously!"]),
    (r"k|ok|okay", ["Cool!"]),
    (r"fine", ["Glad to hear that!"]),
    (r"sure", ["Great!"]),
    (r"maybe", ["That's fair, no rush!"]),
    (r"idk|i dont know", ["That's okay, no pressure."]),
    (r"whatever", ["Alright, moving on!"]),
    (r"cool story", ["Haha, glad you liked it!"]),
    (r"not bad", ["That's good to hear!"]),
    (r"amazing|awesome|great", ["Thanks! I try my best."]),
    (r"boring", ["I'll try to be more interesting!"]),
    (r"lame", ["Ouch! I'll step up my game."]),
    (r"impressive", ["Thanks!"]),
    (r"nice", ["Thank you!"]),
    (r"good one", ["Haha, glad you enjoyed it!"]),
    (r"that was weird", ["Weird can be fun sometimes, right?"]),
    (r"thats sad", ["Yeah, it is..."]),
    (r"im sad", ["I'm here for you if you need to talk."]),
    (r"im happy", ["That's awesome! Happiness is contagious!"]),
    (r"im tired", ["Maybe some rest would help?"]),
    (r"im excited", ["Woo! What for?"]),
    (r"im angry", ["Want to talk about it?"]),
    (r"im stressed", ["I'm here if you need to vent."]),
    (r"im bored", ["Let's find something fun to chat about!"]),
    (r"im confused", ["I'll try to explain better next time!"]),
    (r"im scared", ["I'm here to support you!"]),
    (r"im fine", ["Glad to hear!"]),
    (r"im not sure", ["That's okay, take your time."]),
    (r"thats annoying", ["I'll try to be less annoying next time!"]),
    (r"im done", ["Okay, I get it!"]),
    (r"thats strange", ["Yeah, pretty odd!"]),
    (r"woah chill", ["Haha, okay! I'll calm down."]),
    (r"stop it", ["Oops! Sorry about that."]),
    (r"impressed", ["I'm flattered, thanks!"]),
    (r"thats dumb", ["I'll try harder next time!"]),
    (r"makes sense", ["Glad we're on the same page!"]),
    (r"that was random", ["Yeah, I like keeping things fun!"]),
    (r"what a mess", ["Haha, right?"]),
    (r"im good", ["Great to hear!"]),
    (r"im bad", ["I'm here if you need support."]),
    (r"thats true", ["Yeah, right?"]),
    (r"thats false", ["Okay, noted!"]),
    (r"for real", ["Yep, for real!"]),
    (r"no way", ["Way!"]),
    (r"i doubt it", ["Fair enough."]),
    (r"whatever you say", ["Haha, I mean it!"]),
    (r"you sure", ["Totally sure!"]),
    (r"i guess", ["That works!"]),
    (r"makes no sense", ["I'll try to explain better next time!"]),
    (r"whoa relax", ["Okay, calming down!"]),
    (r"stop", ["Got it!"]),
    (r"that hurts", ["I'm sorry, I didn't mean to upset you."]),
    (r"just kidding", ["Haha, good one!"]),
    (r"im joking", ["I knew it!"]),
    (r"thats wild", ["Yeah, right?"]),
    (r"thats deep", ["Yeah, some thoughts just hit differently."]),
    (r"thats confusing", ["I'll try to be clearer next time."]),
    (r"that was rude", ["I apologize if I seemed rude."]),
    (r"thats sweet", ["Aww, thank you!"]),
    (r"thats kind", ["Thanks! I try my best."]),
    (r"whoa", ["I know, right?"]),
    (r"im tired of this", ["I get it. Want to change topics?"]),
    (r"thats helpful", ["I'm glad I could help!"]),
    (r"that makes me happy", ["I'm glad I could bring some joy!"]),
    (r"that made my day", ["Aww, that's the best compliment ever!"]),
    (r"not helpful", ["I'll try harder next time."]),
    (r"im disappointed", ["I'm sorry to hear that."]),
    (r"im proud of you", ["Thank you! That means a lot."]),
    (r"youre cool", ["Thanks! You're cool too!"]),
    (r"thats embarrassing", ["Haha, it happens!"]),
    (r"im embarrassed", ["Don't worry, it happens to everyone!"]),
    (r"not impressed", ["I'll step up my game!"]),
    (r"im proud of myself", ["You should be! Keep it up!"]),
    (r"thats surprising", ["Yeah, pretty wild huh?"]),
    (r"im speechless", ["Wow! That means a lot."]),
    (r"no hard feelings", ["None at all!"]),
    (r"youre funny", ["Haha, I try!"]),
    (r"youre annoying", ["Oops! I'll tone it down."]),
    (r"youre awesome", ["Thank you! So are you!"]),
    (r"youre weird", ["Weird can be fun!"]),
    (r"youre cute", ["Aww, thanks!"]),
    (r"youre sweet", ["Thank you, I try my best!"]),
    (r"youre mean", ["I'm really sorry! I didn't mean to be."]),
    (r"youre boring", ["I'll try to spice things up!"]),
    (r"youre the best", ["Thank you! You're the best too!"]),
    (r"youre great", ["Aww, thank you!"]),
    (r"youre dumb", ["Hey, I'm still learning!"]),
    (r"youre smart", ["Thanks! I learn from you!"]),
    (r"youre nice", ["Thanks! I try to be."]),
    (r"youre bad", ["I'll try to improve."]),
    (r"youre scary", ["Yikes! I'm just trying to be friendly!"]),





    
]
#fallback response for unmatched input
pairs.append(
    (r"(.*)", ["Oh, it seems I’m not quite grown enough to understand that yet. Can you ask me something else?"])
)

# Function to fix common missing apostrophes
def fix_apostrophes(user_input):
    corrections = {
        r"\bwhats\b": "what's",
        r"\bwhos\b": "who's",
        r"\bwheres\b": "where's",
        r"\bhows\b": "how's",
        r"\bim\b": "I'm",
        r"\bive\b": "I've",
        r"\byoure\b": "you're",
        r"\btheyre\b": "they're",
        r"\bcant\b": "can't",
        r"\bwont\b": "won't",
        r"\bdont\b": "don't",
        r"\bdidnt\b": "didn't",
        r"\bdoesnt\b": "doesn't",
        r"\bshouldnt\b": "shouldn't",
        r"\bwanna\b": "want to",
        r"\bgonna\b": "going to",
        r"\bgimme\b": "give me",
        r"\blemme\b": "let me",
        r"\bdunno\b": "don't know",
        r"\bsup\b": "what's up",
        r"\bwassup\b": "what's up",
        r"\byo\b": "hello",
        r"\bneeda\b": "need to",
        r"\bgotta\b": "got to"
    }
    for pattern, replacement in corrections.items():
        user_input = re.sub(pattern, replacement, user_input, flags=re.IGNORECASE)
    return user_input

# Function to process user input using spaCy for flexible matching
def process_input(user_input):
    user_input = fix_apostrophes(user_input)  # Apply apostrophe corrections
    doc = nlp(user_input)
    max_similarity = 0
    best_response = None

    # Check all pairs for the closest match using similarity
    for pattern, responses in pairs[:-1]:  # Exclude the fallback pair during matching
        pattern_doc = nlp(pattern)
        similarity = doc.similarity(pattern_doc)
        
        if similarity > max_similarity:
            max_similarity = similarity
            best_response = responses

    # If a strong match is found, return it
    if max_similarity > 0.7:  # Adjust threshold if needed
        return best_response

    # Otherwise, return the fallback message
    return pairs[-1][1]  # The fallback message at the bottom of pairs

# Function to start the chatbot
def chatbot():
    print("Hi! I'm Kenny the friendly chatbot. Type 'quit' to end the conversation.")
    
    while True:
        user_input = input("You: ")
        if user_input.lower() == 'quit':
            print("Goodbye!")
            break
        
        # Attempt to get a response with spaCy's flexible matching
        response = process_input(user_input)
        print("Kenny:", response[0])

# Run the chatbot if the script is executed
if __name__ == "__main__":
    chatbot()